apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp-deployment
  labels:
    app: pj-nodeapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pj-nodeapp
  template:
    metadata:
      labels:
        app: pj-nodeapp 
    spec:
      containers:
      - name: pj-nodeapp
        image: pichkul/pj-nodeapp:latest
        ports:
        - containerPort: 3000
